server:
    port: 8084
spring:
    datasource:
        url: jdbc:h2:mem:testSpringDataJPA
        username: sa
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
    application:
        name: emi-management-service
springdoc:
    packages-to-scan: com.cognizant.controller
eureka:
    instance:
        hostname: ${vcap.application.uris[0]:localhost}
        metadataMap:
            instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
        leaseRenewalIntervalInSeconds : 5
    client:
        region : default
        registryFetchIntervalSeconds : 5
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/

